branch-defaults:
  master:
    environment: av-api-env
environment-defaults:
  av-api-env:
    branch: null
    repository: null
global:
  application_name: av-api
  default_ec2_keyname: aws-av-api
  default_platform: 64bit Amazon Linux 2016.09 v2.2.0 running Multi-container Docker
    1.11.2 (Generic)
  default_region: us-west-2
  profile: null
  sc: git
