branch-defaults:
  master:
    environment: av-api-env
environment-defaults:
  av-api-env:
    branch: null
    repository: null
global:
  application_name: av-api
  default_ec2_keyname: aws-av-api
  default_platform: 64bit Amazon Linux 2016.03 v2.1.6 running Docker 1.11.2
  default_region: us-west-2
  profile: null
  sc: git
